"""initial_schema

Revision ID: 3d476b0adf02
Revises:
Create Date: 2026-06-25 16:57:27.303606

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3d476b0adf02"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gateways",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("gateway_uid", sa.String(length=64), nullable=False),
        sa.Column("hmac_secret", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_gateways_gateway_uid"), "gateways", ["gateway_uid"], unique=True
    )
    op.create_index(op.f("ix_gateways_id"), "gateways", ["id"], unique=False)
    op.create_table(
        "hives",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("gateway_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["gateway_id"],
            ["gateways.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_hives_gateway_id"), "hives", ["gateway_id"], unique=False)
    op.create_index(op.f("ix_hives_id"), "hives", ["id"], unique=False)
    op.create_table(
        "hive_levels",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("hive_id", sa.Integer(), nullable=False),
        sa.Column("lower_level_id", sa.Integer(), nullable=True),
        sa.Column("upper_level_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["hive_id"],
            ["hives.id"],
        ),
        sa.ForeignKeyConstraint(
            ["lower_level_id"],
            ["hive_levels.id"],
        ),
        sa.ForeignKeyConstraint(
            ["upper_level_id"],
            ["hive_levels.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_hive_levels_id"), "hive_levels", ["id"], unique=False)
    op.create_table(
        "sensor_devices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("serial_number", sa.String(), nullable=False),
        sa.Column("is_registered", sa.Boolean(), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(), nullable=False),
        sa.Column("hive_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["hive_id"],
            ["hives.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_sensor_devices_id"), "sensor_devices", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_sensor_devices_serial_number"),
        "sensor_devices",
        ["serial_number"],
        unique=True,
    )
    op.create_table(
        "measurements_5m",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("bucket_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("hive_id", sa.Integer(), nullable=True),
        sa.Column("sensor_device_id", sa.Integer(), nullable=False),
        sa.Column("hive_level_id", sa.Integer(), nullable=True),
        sa.Column("avg_value", sa.Float(), nullable=False),
        sa.Column("min_value", sa.Float(), nullable=False),
        sa.Column("max_value", sa.Float(), nullable=False),
        sa.Column("samples_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["hive_id"],
            ["hives.id"],
        ),
        sa.ForeignKeyConstraint(
            ["hive_level_id"],
            ["hive_levels.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sensor_device_id"],
            ["sensor_devices.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "bucket_at",
            "type",
            "hive_id",
            "sensor_device_id",
            "hive_level_id",
            name="uq_measurement_5m_bucket",
        ),
    )
    op.create_index(
        op.f("ix_measurements_5m_bucket_at"),
        "measurements_5m",
        ["bucket_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_measurements_5m_hive_id"), "measurements_5m", ["hive_id"], unique=False
    )
    op.create_index(
        op.f("ix_measurements_5m_hive_level_id"),
        "measurements_5m",
        ["hive_level_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_measurements_5m_id"), "measurements_5m", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_measurements_5m_sensor_device_id"),
        "measurements_5m",
        ["sensor_device_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_measurements_5m_type"), "measurements_5m", ["type"], unique=False
    )
    op.create_table(
        "measurements_raw",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("measured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sensor_device_id", sa.Integer(), nullable=False),
        sa.Column("hive_level_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["hive_level_id"],
            ["hive_levels.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sensor_device_id"],
            ["sensor_devices.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_measurements_raw_hive_level_id"),
        "measurements_raw",
        ["hive_level_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_measurements_raw_id"), "measurements_raw", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_measurements_raw_measured_at"),
        "measurements_raw",
        ["measured_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_measurements_raw_sensor_device_id"),
        "measurements_raw",
        ["sensor_device_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_measurements_raw_type"), "measurements_raw", ["type"], unique=False
    )
    op.create_table(
        "weight_baselines",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("hive_level_id", sa.Integer(), nullable=False),
        sa.Column("computed_at", sa.DateTime(), nullable=False),
        sa.Column("baseline_offset_kg", sa.Float(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("stable_duration_minutes", sa.Integer(), nullable=False),
        sa.Column("algorithm_version", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1", name="ck_weight_baseline_confidence"
        ),
        sa.ForeignKeyConstraint(
            ["hive_level_id"],
            ["hive_levels.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_weight_baselines_computed_at"),
        "weight_baselines",
        ["computed_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_weight_baselines_hive_level_id"),
        "weight_baselines",
        ["hive_level_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_weight_baselines_id"), "weight_baselines", ["id"], unique=False
    )
    op.create_table(
        "weight_reference_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("hive_level_id", sa.Integer(), nullable=False),
        sa.Column("expected_delta_kg", sa.Float(), nullable=False),
        sa.Column("measured_delta_kg", sa.Float(), nullable=False),
        sa.Column("comment", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["hive_level_id"],
            ["hive_levels.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_weight_reference_events_hive_level_id"),
        "weight_reference_events",
        ["hive_level_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_weight_reference_events_id"),
        "weight_reference_events",
        ["id"],
        unique=False,
    )
    op.create_table(
        "weight_calibrations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("hive_level_id", sa.Integer(), nullable=False),
        sa.Column("valid_from", sa.DateTime(), nullable=False),
        sa.Column("valid_to", sa.DateTime(), nullable=True),
        sa.Column("offset_kg", sa.Float(), nullable=False),
        sa.Column("gain", sa.Float(), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "manual", "auto_drift", "reference_weight", name="calibrationsource"
            ),
            nullable=False,
        ),
        sa.Column("algorithm_version", sa.String(), nullable=True),
        sa.Column("reference_event_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("gain > 0", name="ck_weight_calibration_gain_positive"),
        sa.CheckConstraint(
            "valid_to IS NULL OR valid_to > valid_from",
            name="ck_weight_calibration_dates",
        ),
        sa.ForeignKeyConstraint(
            ["hive_level_id"],
            ["hive_levels.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reference_event_id"],
            ["weight_reference_events.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_weight_calibrations_hive_level_id"),
        "weight_calibrations",
        ["hive_level_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_weight_calibrations_id"), "weight_calibrations", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_weight_calibrations_valid_from"),
        "weight_calibrations",
        ["valid_from"],
        unique=False,
    )
    op.create_index(
        op.f("ix_weight_calibrations_valid_to"),
        "weight_calibrations",
        ["valid_to"],
        unique=False,
    )
    op.create_table(
        "measurement_corrected",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("measurement_5m_id", sa.Integer(), nullable=False),
        sa.Column("calibration_id", sa.Integer(), nullable=True),
        sa.Column("raw_weight_kg", sa.Float(), nullable=False),
        sa.Column("corrected_weight_kg", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["calibration_id"],
            ["weight_calibrations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["measurement_5m_id"],
            ["measurements_5m.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_measurement_corrected_calibration_id"),
        "measurement_corrected",
        ["calibration_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_measurement_corrected_measurement_5m_id"),
        "measurement_corrected",
        ["measurement_5m_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_measurement_corrected_measurement_5m_id"),
        table_name="measurement_corrected",
    )
    op.drop_index(
        op.f("ix_measurement_corrected_calibration_id"),
        table_name="measurement_corrected",
    )
    op.drop_table("measurement_corrected")
    op.drop_index(
        op.f("ix_weight_calibrations_valid_to"), table_name="weight_calibrations"
    )
    op.drop_index(
        op.f("ix_weight_calibrations_valid_from"), table_name="weight_calibrations"
    )
    op.drop_index(op.f("ix_weight_calibrations_id"), table_name="weight_calibrations")
    op.drop_index(
        op.f("ix_weight_calibrations_hive_level_id"), table_name="weight_calibrations"
    )
    op.drop_table("weight_calibrations")
    op.drop_index(
        op.f("ix_weight_reference_events_id"), table_name="weight_reference_events"
    )
    op.drop_index(
        op.f("ix_weight_reference_events_hive_level_id"),
        table_name="weight_reference_events",
    )
    op.drop_table("weight_reference_events")
    op.drop_index(op.f("ix_weight_baselines_id"), table_name="weight_baselines")
    op.drop_index(
        op.f("ix_weight_baselines_hive_level_id"), table_name="weight_baselines"
    )
    op.drop_index(
        op.f("ix_weight_baselines_computed_at"), table_name="weight_baselines"
    )
    op.drop_table("weight_baselines")
    op.drop_index(op.f("ix_measurements_raw_type"), table_name="measurements_raw")
    op.drop_index(
        op.f("ix_measurements_raw_sensor_device_id"), table_name="measurements_raw"
    )
    op.drop_index(
        op.f("ix_measurements_raw_measured_at"), table_name="measurements_raw"
    )
    op.drop_index(op.f("ix_measurements_raw_id"), table_name="measurements_raw")
    op.drop_index(
        op.f("ix_measurements_raw_hive_level_id"), table_name="measurements_raw"
    )
    op.drop_table("measurements_raw")
    op.drop_index(op.f("ix_measurements_5m_type"), table_name="measurements_5m")
    op.drop_index(
        op.f("ix_measurements_5m_sensor_device_id"), table_name="measurements_5m"
    )
    op.drop_index(op.f("ix_measurements_5m_id"), table_name="measurements_5m")
    op.drop_index(
        op.f("ix_measurements_5m_hive_level_id"), table_name="measurements_5m"
    )
    op.drop_index(op.f("ix_measurements_5m_hive_id"), table_name="measurements_5m")
    op.drop_index(op.f("ix_measurements_5m_bucket_at"), table_name="measurements_5m")
    op.drop_table("measurements_5m")
    op.drop_index(op.f("ix_sensor_devices_serial_number"), table_name="sensor_devices")
    op.drop_index(op.f("ix_sensor_devices_id"), table_name="sensor_devices")
    op.drop_table("sensor_devices")
    op.drop_index(op.f("ix_hive_levels_id"), table_name="hive_levels")
    op.drop_table("hive_levels")
    op.drop_index(op.f("ix_hives_id"), table_name="hives")
    op.drop_index(op.f("ix_hives_gateway_id"), table_name="hives")
    op.drop_table("hives")
    op.drop_index(op.f("ix_gateways_id"), table_name="gateways")
    op.drop_index(op.f("ix_gateways_gateway_uid"), table_name="gateways")
    op.drop_table("gateways")
    # ### end Alembic commands ###
