"""add weight calibration models

Revision ID: 40b33fb3a045
Revises: 73d4661c7e0c
Create Date: 2026-06-09 23:25:12.203711

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "40b33fb3a045"
down_revision: Union[str, Sequence[str], None] = "73d4661c7e0c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "weight_calibrations",
        sa.Column("reference_event_id", sa.Integer(), nullable=True),
    )
    op.create_foreign_key(
        None,
        "weight_calibrations",
        "weight_reference_events",
        ["reference_event_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("nom_temporaire", "weight_calibrations", type_="foreignkey")
    op.drop_column("weight_calibrations", "reference_event_id")
    # ### end Alembic commands ###
