"""init schema

Revision ID: 4f77b285e4f0
Revises:
Create Date: 2026-05-22 21:53:55.708288

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4f77b285e4f0"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hives",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_hives_id"), "hives", ["id"], unique=False)
    op.create_table(
        "hive_levels",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("hive_id", sa.Integer(), nullable=False),
        sa.Column("lower_level_id", sa.Integer(), nullable=True),
        sa.Column("upper_level_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["hive_id"],
            ["hives.id"],
        ),
        sa.ForeignKeyConstraint(
            ["lower_level_id"],
            ["hive_levels.id"],
        ),
        sa.ForeignKeyConstraint(
            ["upper_level_id"],
            ["hive_levels.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_hive_levels_id"), "hive_levels", ["id"], unique=False)
    op.create_table(
        "sensor_devices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("serial_number", sa.String(), nullable=False),
        sa.Column("is_registered", sa.Boolean(), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(), nullable=False),
        sa.Column("hive_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["hive_id"],
            ["hives.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_sensor_devices_id"), "sensor_devices", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_sensor_devices_serial_number"),
        "sensor_devices",
        ["serial_number"],
        unique=True,
    )
    op.create_table(
        "measurements",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("measured_at", sa.DateTime(), nullable=False),
        sa.Column("sensor_device_id", sa.Integer(), nullable=False),
        sa.Column("hive_level_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["hive_level_id"],
            ["hive_levels.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sensor_device_id"],
            ["sensor_devices.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_measurements_id"), "measurements", ["id"], unique=False)
    op.create_index(
        op.f("ix_measurements_measured_at"),
        "measurements",
        ["measured_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_measurements_type"), "measurements", ["type"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_measurements_type"), table_name="measurements")
    op.drop_index(op.f("ix_measurements_measured_at"), table_name="measurements")
    op.drop_index(op.f("ix_measurements_id"), table_name="measurements")
    op.drop_table("measurements")
    op.drop_index(op.f("ix_sensor_devices_serial_number"), table_name="sensor_devices")
    op.drop_index(op.f("ix_sensor_devices_id"), table_name="sensor_devices")
    op.drop_table("sensor_devices")
    op.drop_index(op.f("ix_hive_levels_id"), table_name="hive_levels")
    op.drop_table("hive_levels")
    op.drop_index(op.f("ix_hives_id"), table_name="hives")
    op.drop_table("hives")
    # ### end Alembic commands ###
