"""measurement corrected

Revision ID: 68741b8f114f
Revises: 40b33fb3a045
Create Date: 2026-06-16 22:45:07.330119

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "68741b8f114f"
down_revision: Union[str, Sequence[str], None] = "40b33fb3a045"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "measurement_corrected",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("measurement_5m_id", sa.Integer(), nullable=False),
        sa.Column("calibration_id", sa.Integer(), nullable=False),
        sa.Column("raw_weight_kg", sa.Float(), nullable=False),
        sa.Column("corrected_weight_kg", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["calibration_id"],
            ["weight_calibrations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["measurement_5m_id"],
            ["measurements_5m.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_measurement_corrected_calibration_id"),
        "measurement_corrected",
        ["calibration_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_measurement_corrected_measurement_5m_id"),
        "measurement_corrected",
        ["measurement_5m_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
   
    op.drop_index(
        op.f("ix_measurement_corrected_measurement_5m_id"),
        table_name="measurement_corrected",
    )
    op.drop_index(
        op.f("ix_measurement_corrected_calibration_id"),
        table_name="measurement_corrected",
    )
    op.drop_table("measurement_corrected")
    # ### end Alembic commands ###
