"""add weight calibration models

Revision ID: 73d4661c7e0c
Revises: 8f2e40193f10
Create Date: 2026-06-09 00:06:20.049821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73d4661c7e0c'
down_revision: Union[str, Sequence[str], None] = '8f2e40193f10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weight_baselines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hive_level_id', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.Column('baseline_offset_kg', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('stable_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('algorithm_version', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_weight_baseline_confidence'),
    sa.ForeignKeyConstraint(['hive_level_id'], ['hive_levels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weight_baselines_computed_at'), 'weight_baselines', ['computed_at'], unique=False)
    op.create_index(op.f('ix_weight_baselines_hive_level_id'), 'weight_baselines', ['hive_level_id'], unique=False)
    op.create_index(op.f('ix_weight_baselines_id'), 'weight_baselines', ['id'], unique=False)
    op.create_table('weight_calibrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hive_level_id', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.DateTime(), nullable=False),
    sa.Column('valid_to', sa.DateTime(), nullable=True),
    sa.Column('offset_kg', sa.Float(), nullable=False),
    sa.Column('gain', sa.Float(), nullable=False),
    sa.Column('source', sa.Enum('manual', 'auto_drift', 'reference_weight', name='calibrationsource'), nullable=False),
    sa.Column('algorithm_version', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('valid_to IS NULL OR valid_to > valid_from', name='ck_weight_calibration_dates'),
    sa.ForeignKeyConstraint(['hive_level_id'], ['hive_levels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weight_calibrations_hive_level_id'), 'weight_calibrations', ['hive_level_id'], unique=False)
    op.create_index(op.f('ix_weight_calibrations_id'), 'weight_calibrations', ['id'], unique=False)
    op.create_index(op.f('ix_weight_calibrations_valid_from'), 'weight_calibrations', ['valid_from'], unique=False)
    op.create_index(op.f('ix_weight_calibrations_valid_to'), 'weight_calibrations', ['valid_to'], unique=False)
    op.create_table('weight_reference_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hive_level_id', sa.Integer(), nullable=False),
    sa.Column('expected_delta_kg', sa.Float(), nullable=False),
    sa.Column('measured_delta_kg', sa.Float(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hive_level_id'], ['hive_levels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weight_reference_events_hive_level_id'), 'weight_reference_events', ['hive_level_id'], unique=False)
    op.create_index(op.f('ix_weight_reference_events_id'), 'weight_reference_events', ['id'], unique=False)
    op.drop_constraint(op.f('uq_measurement_5m_bucket'), 'measurements_5m', type_='unique')
    op.create_unique_constraint('uq_measurement_5m_bucket', 'measurements_5m', ['bucket_at', 'type', 'hive_id', 'sensor_device_id', 'hive_level_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_measurement_5m_bucket', 'measurements_5m', type_='unique')
    op.create_unique_constraint(op.f('uq_measurement_5m_bucket'), 'measurements_5m', ['bucket_at', 'type', 'sensor_device_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_weight_reference_events_id'), table_name='weight_reference_events')
    op.drop_index(op.f('ix_weight_reference_events_hive_level_id'), table_name='weight_reference_events')
    op.drop_table('weight_reference_events')
    op.drop_index(op.f('ix_weight_calibrations_valid_to'), table_name='weight_calibrations')
    op.drop_index(op.f('ix_weight_calibrations_valid_from'), table_name='weight_calibrations')
    op.drop_index(op.f('ix_weight_calibrations_id'), table_name='weight_calibrations')
    op.drop_index(op.f('ix_weight_calibrations_hive_level_id'), table_name='weight_calibrations')
    op.drop_table('weight_calibrations')
    op.drop_index(op.f('ix_weight_baselines_id'), table_name='weight_baselines')
    op.drop_index(op.f('ix_weight_baselines_hive_level_id'), table_name='weight_baselines')
    op.drop_index(op.f('ix_weight_baselines_computed_at'), table_name='weight_baselines')
    op.drop_table('weight_baselines')
    # ### end Alembic commands ###
