"""add measurement 5m

Revision ID: 8f2e40193f10
Revises: a1857ad55934
Create Date: 2026-05-27 20:59:00.594527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8f2e40193f10'
down_revision: Union[str, Sequence[str], None] = 'a1857ad55934'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_measurements_id'), table_name='measurements')
    op.drop_index(op.f('ix_measurements_measured_at'), table_name='measurements')
    op.drop_index(op.f('ix_measurements_type'), table_name='measurements')
    op.drop_table('measurements')
    op.add_column('measurements_5m', sa.Column('hive_id', sa.Integer(), nullable=True))
    op.add_column(
        "measurements_5m",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
    )
    op.create_index(op.f('ix_measurements_5m_hive_id'), 'measurements_5m', ['hive_id'], unique=False)
    op.create_index(op.f('ix_measurements_5m_hive_level_id'), 'measurements_5m', ['hive_level_id'], unique=False)
    op.create_index(op.f('ix_measurements_5m_id'), 'measurements_5m', ['id'], unique=False)
    op.create_index(op.f('ix_measurements_5m_sensor_device_id'), 'measurements_5m', ['sensor_device_id'], unique=False)
    op.create_index(op.f('ix_measurements_5m_type'), 'measurements_5m', ['type'], unique=False)
    op.create_unique_constraint(
        "uq_measurement_5m_bucket",
        "measurements_5m",
        [
            "bucket_at",
            "type",
            "sensor_device_id",
        ],
    )
    op.create_foreign_key(None, 'measurements_5m', 'hives', ['hive_id'], ['id'])
    op.create_index(op.f('ix_measurements_raw_hive_level_id'), 'measurements_raw', ['hive_level_id'], unique=False)
    op.create_index(op.f('ix_measurements_raw_id'), 'measurements_raw', ['id'], unique=False)
    op.create_index(op.f('ix_measurements_raw_sensor_device_id'), 'measurements_raw', ['sensor_device_id'], unique=False)
    op.create_index(op.f('ix_measurements_raw_type'), 'measurements_raw', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_measurements_raw_type'), table_name='measurements_raw')
    op.drop_index(op.f('ix_measurements_raw_sensor_device_id'), table_name='measurements_raw')
    op.drop_index(op.f('ix_measurements_raw_id'), table_name='measurements_raw')
    op.drop_index(op.f('ix_measurements_raw_hive_level_id'), table_name='measurements_raw')
    op.drop_constraint(None, 'measurements_5m', type_='foreignkey')
    op.drop_index(op.f('ix_measurements_5m_type'), table_name='measurements_5m')
    op.drop_index(op.f('ix_measurements_5m_sensor_device_id'), table_name='measurements_5m')
    op.drop_index(op.f('ix_measurements_5m_id'), table_name='measurements_5m')
    op.drop_index(op.f('ix_measurements_5m_hive_level_id'), table_name='measurements_5m')
    op.drop_index(op.f('ix_measurements_5m_hive_id'), table_name='measurements_5m')
    op.drop_column('measurements_5m', 'created_at')
    op.drop_column('measurements_5m', 'hive_id')
    op.create_table('measurements',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('measured_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('sensor_device_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('hive_level_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['hive_level_id'], ['hive_levels.id'], name=op.f('measurements_hive_level_id_fkey')),
    sa.ForeignKeyConstraint(['sensor_device_id'], ['sensor_devices.id'], name=op.f('measurements_sensor_device_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('measurements_pkey'))
    )
    op.create_index(op.f('ix_measurements_type'), 'measurements', ['type'], unique=False)
    op.create_index(op.f('ix_measurements_measured_at'), 'measurements', ['measured_at'], unique=False)
    op.create_index(op.f('ix_measurements_id'), 'measurements', ['id'], unique=False)
    # ### end Alembic commands ###
