services:
  # =====================================================
  # API FastAPI
  # =====================================================
  api:
    build: ./api

    environment:
      ENV: dev

      # =================================================
      # IMPORTANT :
      # En dev on utilise AUSSI TimescaleDB
      # =================================================
      DATABASE_URL: postgresql+psycopg://beibeilles:beibeilles@timescaledb:5432/beibeilles

    ports:
      - "8000:8000"

    volumes:
      - ./api:/app

    depends_on:
      timescaledb:
        condition: service_healthy

  # =====================================================
  # Dashboard Plotly
  # =====================================================
  dash:
    build: ./dash_app

    environment:
      API_URL: http://localhost:8000

    ports:
      - "8050:8050"

    volumes:
      - ./dash_app:/app

    depends_on:
      - api

  # =====================================================
  # TimescaleDB local
  # =====================================================
  timescaledb:
    image: timescale/timescaledb:latest-pg16

    environment:
      POSTGRES_USER: beibeilles
      POSTGRES_PASSWORD: beibeilles
      POSTGRES_DB: beibeilles

    ports:
      - "5432:5432"

    volumes:
      - timescaledb_dev_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U beibeilles -d beibeilles"]
      interval: 5s
      timeout: 5s
      retries: 10

# =======================================================
# Volume persistant DEV
# =======================================================
volumes:
  timescaledb_dev_data:
