services:
  timescaledb:
    ports:
      - "127.0.0.1:5432:5432"

  api:
    image: ghcr.io/tgalton/beibeilles-api:latest
    container_name: beibeilles-api
    pull_policy: always
    environment:
      ENV: prod
      DATABASE_URL: postgresql+psycopg://beibeilles:beibeilles@timescaledb:5432/beibeilles
    ports:
      - "8000:8000"

  dash:
    image: ghcr.io/tgalton/beibeilles-dash:latest
    container_name: beibeilles-dash
    pull_policy: always
    environment:
      API_URL: http://api:8000
    ports:
      - "8050:8050"

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
    environment:
      - DOCKER_API_VERSION=1.44
