# Docker compose prod
services:
  timescaledb:
    ports:
      - "127.0.0.1:5432:5432"

  api:
    image: ghcr.io/tgalton/beibeilles-api:latest
    container_name: beibeilles-api
    pull_policy: always
    environment:
      ENV: prod
      DATABASE_URL: postgresql+psycopg://beibeilles:beibeilles@timescaledb:5432/beibeilles
    ports:
      - "8000:8000"

  dash:
    image: ghcr.io/tgalton/beibeilles-dash:latest
    container_name: beibeilles-dash
    pull_policy: always
    environment:
      API_URL: http://api:8000
    ports:
      - "8050:8050"

  # Nouveau service aggregator
  aggregator:
    image: ghcr.io/tgalton/beibeilles-api:latest

    restart: always

    environment:
      DATABASE_URL: postgresql+psycopg://beibeilles:beibeilles@timescaledb:5432/beibeilles

    depends_on:
      timescaledb:
        condition: service_healthy

    command: >
      sh -c "
        while true;
        do
          echo 'Aggregation started';
          python scripts/aggregate_measurements_5m.py;
          echo 'Aggregation finished';
          sleep 300;
        done
      "

  # Nouveau service cleanup
  cleanup:
    image: ghcr.io/tgalton/beibeilles-api:latest

    restart: always

    environment:
      DATABASE_URL: postgresql+psycopg://beibeilles:beibeilles@timescaledb:5432/beibeilles

    depends_on:
      timescaledb:
        condition: service_healthy

    command: >
      sh -c "
        while true;
        do
          python scripts/delete_raw_after_7days.py;
          sleep 86400;
        done
      "

  # Nouveau service calibration
  auto-recalibration:
    image: ghcr.io/tgalton/beibeilles-api:latest

    restart: always

    environment:
      DATABASE_URL: postgresql+psycopg://beibeilles:beibeilles@timescaledb:5432/beibeilles

    depends_on:
      timescaledb:
        condition: service_healthy

    command: >
      sh -c "
        while true;
        do
          python scripts/run_auto_recalibration.py;
          sleep 300;
        done
      "

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
    environment:
      - DOCKER_API_VERSION=1.44
