name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # =====================================================
      # Installation dépendances API
      # =====================================================
      - name: Install API dependencies
        run: |
          cd api
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # =====================================================
      # Vérification Ruff
      # =====================================================
      - name: Ruff check
        run: |
          cd api
          ruff check .

      # =====================================================
      # Vérification typing
      # =====================================================
      - name: MyPy check
        run: |
          cd api
          mypy app

      # =====================================================
      # Vérifie que FastAPI démarre correctement
      # =====================================================
      - name: Validate FastAPI startup
        run: |
          cd api
          python -c "from app.main import app"

      # =====================================================
      # Vérifie qu'Alembic charge correctement
      # IMPORTANT :
      # évite les mauvaises surprises en prod
      # =====================================================
      - name: Validate Alembic migrations
        env:
          DATABASE_URL: sqlite:///./ci_test.db
          PYTHONPATH: .
        run: |
          cd api
          alembic upgrade head
      # =====================================================
      # Login GitHub Container Registry
      # =====================================================
      - name: Login to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u tgalton --password-stdin

      # =====================================================
      # Build + Push API
      # =====================================================
      - name: Build API image
        run: |
          docker build -t ghcr.io/tgalton/beibeilles-api:latest ./api
          docker push ghcr.io/tgalton/beibeilles-api:latest

      # =====================================================
      # Build + Push Dash
      # =====================================================
      - name: Build Dash image
        run: |
          docker build -t ghcr.io/tgalton/beibeilles-dash:latest ./dash_app
          docker push ghcr.io/tgalton/beibeilles-dash:latest
